### ISSUE TITLE
Add metadata info on rubygems.org

### ISSUE THREAD

**Issue by JuanitoFatas** [plexus/typecheck#1]
Hey Arne, could you please also add some metadata information of this gem in this page https://rubygems.org/gems/typecheck/edit :pray::

Here are some I know:

| URL | VALUE |
| --- | --- |
| **Source Code URL** | https://github.com/plexus/typecheck |
| **Documentation URL** | http://www.rubydoc.info/gems/typecheck |
| **Bug Tracker URL** | https://github.com/plexus/typecheck/issues |
| **Wiki URL** | https://github.com/plexus/typecheck/wiki |

Thank you! :bear:

**Comment by plexus** [comment]
done. closing #1

On Fri, Mar 13, 2015 at 6:26 AM, Juanito Fatas notifications@github.com
wrote:

> Hey Arne, could you please also add some metadata information of this gem
> in this page https://rubygems.org/gems/typecheck/edit [image: :pray:]:
> 
> Here are some I know:
>   URL VALUE   _Source Code URL_ https://github.com/plexus/typecheck  _Documentation
> URL_ http://www.rubydoc.info/gems/typecheck  _Bug Tracker URL_
> https://github.com/plexus/typecheck/issues  _Wiki URL_
> https://github.com/plexus/typecheck/wiki
> 
> Thank you! [image: :bear:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/plexus/typecheck/issues/1.

## 

| @plexus https://twitter.com/plexus  | arnebrasseur.net | The Happy
Lambda https://leanpub.com/happylambda |
